apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring4shell
    app.kubernetes.io/component: spring4shell
    app.kubernetes.io/instance: spring4shell
    app.kubernetes.io/name: spring4shell
    app.kubernetes.io/part-of: spring4shell
    app.openshift.io/runtime-namespace: app-deploy
  name: spring4shell
  namespace: app-deploy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring4shell
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: spring4shell
        deployment: spring4shell
    spec:
      containers:
      - image: quay.io/smileyfritz/spring4shell:v0.5
        imagePullPolicy: IfNotPresent
        name: spring4shell
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
